- src/apify_client/_errors.py
- src/apify_client/_http_client.py
When attempting to retrieve a non-existing record from a key-value store, we get an error directly from S3, which is XML-formatted, instead of from our API servers, which return it in JSON. This fixes the parsing of those errors, enabling correct behaviour (returning None) for those missing records.
I've also set the default `Accept` header to `application/json, */*`, in order to prefer JSON responses and maintain compatibility with the JS client.
> Fix parsing errors from S3

- src/apify_client/_utils.py
- src/apify_client/client.py
- tests/unit/test_utils.py
I forgot to pass those arguments when I implemented them, oops.
> Fix max_retries and min_delay_between_retries_millis in HTTP client

- src/apify_client/_consts.py
- src/apify_client/client.py
- src/apify_client/clients/base/actor_job_base_client.py
- src/apify_client/clients/resource_clients/build.py
This PR adds a sub-client for manipulating a single actor build, mimicking the methods that exist on JS client.
> Add client for manipulating a single build object

- lint_and_test.sh
- src/apify_client/_utils.py
- src/apify_client/client.py
- src/apify_client/clients/resource_clients/schedule.py
- src/apify_client/clients/resource_clients/schedule_collection.py
Subclient for manipulating single schedule or schedule collection.
Note that I had to get a bit creative in `create` function in `ScheduleCollectionClient`. The arguments listed in API docs (https://docs.apify.com/api/v2#/reference/schedules/schedules-collection/create-schedule) are not 100% accurate. `cronExpression`, `isEnabled` and `isExclusive` seem to be required and also it seems it doesn't matter what `userId` you pass, it'll be set based on token.
> Schedule subclient

- src/apify_client/_http_client.py
- src/apify_client/client.py
The API server now supports authorizing with a token sent in the `Authorization` header for improved security, so this PR adds support for sending it that way.
> Send API token in the Authorization header instead of as a request parameter

- docs/docs.md
- src/apify_client/clients/resource_clients/dataset.py
We're using keyword-only arguments for all arguments in all the complicated functions except these three, let's fix and unify that.
> Fix keyword-only argument usage in some dataset-client functions

- CHANGELOG.md
- setup.py
- src/apify_client/_utils.py
- src/apify_client/clients/base/base_client.py
- src/apify_client/clients/resource_clients/run.py
- src/apify_client/clients/resource_clients/task.py
- src/apify_client/clients/resource_clients/task_collection.py
- src/apify_client/clients/resource_clients/webhook.py
I added the package `flake8-quotes` as a development dependency, it enforces the use of single-quotes by default through linting, and I fixed all the violations that were present in the code, as it makes it a bit cleaner and unified.
> Enforce use of single-quotes via lint plugin

- .github/workflows/release.yml
- CHANGELOG.md
There is a [PR in the `apify-actor-docker`](https://github.com/apify/apify-actor-docker/pull/57) repo which adds support for building actor images with this client preinstalled. This PR only adds a few steps to the release workflow of this client to call the build of those actor images when releasing a new version of the client.
This PR should be merged only after the PR in `apify-actor-docker` is merged.
> Call building of actor images containing this client when doing a new release

- .github/workflows/release.yml
- CHANGELOG.md
Apify SDK uses `latest` and `beta` tags, but this client used `stable` and `beta` tags.
I've changed it so that this client uses the same tags as the Apify SDK (which is the correct way since `latest` has a special meaning in Docker repos).
> Change tags for actor images to align with Apify SDK Node.js images

- CHANGELOG.md
- docs/docs.md
- src/apify_client/clients/base/actor_job_base_client.py
- src/apify_client/clients/resource_clients/run.py
The API now supports specifying this parameter, so I'm adding it to the client as well.
> Add the `gracefully` parameter to the "Abort run" method

- CHANGELOG.md
- src/apify_client/clients/base/actor_job_base_client.py
It slept 250 seconds instead of 250 milliseconds.
> Fix wrong value in `time.sleep` between successive requests in the `wait_for_finish` method

- CHANGELOG.md
- docs/docs.md
- docs/res/intro.md
- src/apify_client/clients/resource_clients/dataset.py
- src/apify_client/clients/resource_clients/key_value_store.py
- src/apify_client/clients/resource_clients/log.py
With the implementation of the Apify SDK for Python, we will have to do some bigger changes to the Python Client, so now is a good time to take some time and get rid of some old problems, before we are stuck with them forever. One of them is that streaming methods for some resources (dataset items, key-value store records and log contents) are a mess.
This unifies their behavior, and makes them safer by forcing them to return a context-managed object, so the streaming response is automatically closed after use.
It also unifies the naming and behavior of methods for fetching the resource contents as raw bytes, by naming them all in the `get_as_bytes` style, instead of the varying names and usages they had before.
> Unified methods for streaming resources

- CHANGELOG.md
- docs/docs.md
- docs/res/intro.md
- setup.py
- src/apify_client/_errors.py
- src/apify_client/_http_client.py
- src/apify_client/clients/resource_clients/dataset.py
- src/apify_client/clients/resource_clients/key_value_store.py
- src/apify_client/clients/resource_clients/log.py
We want to introduce `async` mode to the client, so that users can make non-blocking requests using `asyncio`. To achieve that, we have to replace the underlying HTTP library, since `requests` does not have `async` support.
I'm switching it to [`httpx`](https://github.com/encode/httpx/) here. It's a fairly mature HTTP(S) library, with support for both sync and async operation, and all the features we need, and it has a (mostly) `requests`-compatible interface, so the switch is fairly easy.
There should be basically no functional differences, but still I'm marking the change as breaking, since under the hood it uses `httpcore` on the transport layer, but `requests` uses `urllib3`, so there could be some low level changes which could possibly affect someone.
> Switched underlying HTTP library from `requests` to `httpx`

- CHANGELOG.md
- docs/docs.md
- docs/res/intro.md
- src/apify_client/_http_client.py
- src/apify_client/_logging.py
- src/apify_client/clients/base/base_client.py
Logging was missing for a long time from the client, and it made it harder to debug the client.
This adds some basic logging to the HTTP calls, using the standard Python logger, enriched by contextual information from the client methods which are doing the HTTP calls by some funky metaclass programming.
There is a `_DebugLogFormatter` class which is great for testing, used like this:
```python
import logging
from apify_client._logging import _DebugLogFormatter
client_logger = logging.getLogger('apify_client')
client_logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
handler.setFormatter(_DebugLogFormatter())
client_logger.addHandler(handler)
```
> Added logger with basic debugging info

- CHANGELOG.md
- src/apify_client/_http_client.py
- src/apify_client/_utils.py
If you tried to push an item which contained a `NaN` to a dataset, it would return an error from the Apify API, that the JSON you sent to it is invalid.
```python
>>> client.dataset('~nan-testing-dataset').push_items([{ 'a': float('NaN')}])
ApifyApiError: Cannot parse POST payload as JSON: Unexpected token N in JSON at position 7
```
That is because in Python, by default, `json.dumps()` stringifies `NaN` and `Infinity` values. This is against the JSON standard, and `JSON.parse` on the API fails to parse the value.
This fixes it by adding the `allow_nan=False` parameter to `json.dumps()`, so that the error is caught before sending the invalid JSON to the API, and throws an error early.
```python
>>> client.dataset('~nan-testing-dataset').push_items([{ 'a': float('NaN')}])
ValueError: Out …
```
> Disallowed `NaN` and `Infinity` values in JSONs sent to the Apify API

- .isort.cfg
- CHANGELOG.md
- setup.py
- tests/unit/test_utils.py
This is to bring consistency with the Python SDK, which is also converting to `pytest`-style tests [here](https://github.com/apify/apify-sdk-python/pull/16).
> Converted `unittest`-style tests to `pytest`-style tests

- src/apify_client/clients/resource_clients/user.py
The previous code didn't work since we always pass something into `resource_id` from the `.user()` call (the type is `str | None`). This way, we always popped something from `kwargs` and `'me'` could never make it to the URL. 
Now, it will just check whether the value is `None` or not and replace it with `'me'` if it's `None`
> fix: Calling user().get() will use '/me' endpoint correctly

- CHANGELOG.md
- docs/docs.md
- pyproject.toml
- scripts/check_async_docstrings.py
- scripts/fix_async_docstrings.py
- src/apify_client/clients/base/base_client.py
- src/apify_client/clients/resource_clients/request_queue.py
- tests/integration/test_request_queue.py
Python code after a long time, rather check it carefully. 😄
> feat: add list_and_lock_head, delete_request_lock, prolong_request_lock, batch_add_requests, batch_delete_requests and list_requests methods

- .github/workflows/check_docs.yaml
- .github/workflows/integration_tests.yaml
- .github/workflows/lint_and_type_checks.yaml
- .github/workflows/pr_toolkit.yaml
- .github/workflows/release.yaml
- .github/workflows/unit_tests.yaml
- .pre-commit-config.yaml
- mypy.ini
- pytest.ini
> Unify indentation in configuration files

- docs/docs.md
- src/apify_client/clients/base/actor_job_base_client.py
- src/apify_client/clients/resource_clients/run.py
- Closes #137
- I implement the reboot method in the same way as other methods calling endpoints (e.g. abort).
- @fnesveda, @jirimoravcik: guys could you please give me some advice on how could I test it?
I tried the following: Get the object of type `RunClient` using the `last_run()` method called on the specific Actor. And then call on it the `reboot()` method...
```python
from src.apify_client import ApifyClient
API_TOKEN = 'todo'
ACTOR_ID = 'apify/beautifulsoup-scraper'
apify_client = ApifyClient(API_TOKEN)
print(apify_client)
actor_client = apify_client.actor(ACTOR_ID)
print(actor_client)
last_run = actor_client.last_run()
print(last_run)
result = last_run.reboot()
print(result)
```
However, it does not work, and I got the unknown URL exception (full traceback below). The example of …
> Add actor reboot method to the RunClient

- CHANGELOG.md
- pyproject.toml
- src/apify_client/_http_client.py
- src/apify_client/_logging.py
There were some issues in how the requests were logged through our logger, namely:
- the URL in the log was the URL of the resource the request was made to, but not the action on the resource (`RunClient.reboot()` would log URL `https://api.apify.com/v2/actor-runs/RUN_ID`, without the `/reboot` at the end)
- `ApifyClient` and `ApifyClientAsync` had different log messages and details
- the request attempt and method were not logged
This fixes all of that.
> Improve logging of HTTP requests

- CHANGELOG.md
- pyproject.toml
This removes the `pytest-randomly` Pytest plugin, as it doesn't play nice with `pytest-xdist`.
`pytest-randomly` (among other things) sets the random seed in the beginning of the tests to the current datetime. `pytest-xdist` runs the tests in parallel in multiple runners. When you use these two together, it happens that all of the runners have the same random seed, so if you e.g. [generate random resource names](https://github.com/apify/apify-client-python/blob/13c029e82731138cf67912fe6b375ab61846d4c5/tests/integration/test_request_queue.py#L7-L12), all runners will generate the same ones, leading to conflicts.
The other feature of `pytest-randomly`, running the tests in random order to ensure that the tests are not passing just because of some side effects caused by running in a specific …
> Stop using `pytest-randomly` in tests

- CHANGELOG.md
- docs/docs.md
- src/apify_client/clients/resource_clients/actor.py
- src/apify_client/clients/resource_clients/actor_collection.py
- src/apify_client/clients/resource_clients/task.py
- src/apify_client/clients/resource_clients/task_collection.py
When we introduced pay-per result Actors, we did not add support for specifying the max items limit to the Python API client. This adds it hopefully everywhere it's supported.
Closes #146.
> Add support for specifying the `max_items` parameter for pay-per result Actors and their runs

- .github/workflows/check_docs.yaml
- .github/workflows/integration_tests.yaml
- .github/workflows/lint_and_type_checks.yaml
- .github/workflows/release.yaml
- .github/workflows/unit_tests.yaml
- CHANGELOG.md
- docs/docs.md
- src/apify_client/client.py
- src/apify_client/clients/__init__.py
- src/apify_client/clients/resource_clients/__init__.py
- src/apify_client/clients/resource_clients/store_collection.py
- tests/integration/test_store.py
- Added new methods for https://docs.apify.com/api/v2/#/reference/store/store-actors-collection
- Updated actions/checkout across GH workflows because https://github.com/actions/checkout/issues/1448#issuecomment-1705344036
> feat: Added StoreCollectionClient for listing Actors in Apify store

- .github/workflows/check_version_availability.yaml
- .github/workflows/run_checks.yaml
- Makefile
- scripts/check_version_availability.py
- scripts/update_version_for_prerelease.py
- scripts/utils.py
We have a recurring issue that you often forget to bump the package version number in a PR, and then when you merge it to `master`, the package publication fails because the version you're trying to publish already exists.
This adds a check to CI which detects these issues early and fails the CI, so you can't merge those PRs without bumping the package version number.
It gets skipped if the title of the PR is `docs: ...`, because such PRs don't trigger package publication when merged.
Same as https://github.com/apify/apify-sdk-python/pull/127.
> chore: Check whether version in PR is already released

- pyproject.toml
- src/apify_client/_utils.py
Use `>=` rather than `~=` for general dependencies.
See https://github.com/apify/apify-sdk-python/pull/154 for context.
Also updates ruff config from Apify SDK Python.
> Add comment why not to use `~=` clause in deps definition

- CHANGELOG.md
- src/apify_client/clients/resource_clients/build.py
This wraps the new `/actor-builds/:build_id/log` endpoint. See [API reference](https://docs.apify.com/api/v2/#/reference/actor-builds/build-log/get-log) for more information.
> feat: add log() method to BuildClient (Python)

- pyproject.toml
Same hotfix as in https://github.com/apify/apify-sdk-python/pull/195.
> docs: freeze dependencies of docs build

- CHANGELOG.md
- pyproject.toml
- src/apify_client/clients/resource_clients/actor.py
- src/apify_client/clients/resource_clients/task.py
- Resulting in:
```
apify_client._errors.ApifyApiError: We have bad news: there is no API endpoint at this URL. 
Did you specify it correctly?
```
- Code to reproduce it:
```python
from apify_client import ApifyClient
TOKEN = '...'
ACTOR_ID = '...'
def actor_run_abort(apify_client: ApifyClient, actor_id: str) -> None:
actor_client = apify_client.actor(actor_id)
actor_client.call(wait_secs=1)
last_run = actor_client.last_run(status='RUNNING', origin='API')
aborted_info = last_run.abort()
print(f'aborted_info: {aborted_info}')
if __name__ == '__main__':
apify_client = ApifyClient(TOKEN)
actor_run_abort(apify_client, ACTOR_ID)   
```
```python
import asyncio
from apify_client import ApifyClientAsync
TOKEN = '...'
ACTOR_ID = '...'
async def actor_run_abort_async(apify_client: …
```
> fix: aborting of last Actor/task run

- CHANGELOG.md
- src/apify_client/clients/resource_clients/actor.py
- src/apify_client/clients/resource_clients/task.py
- Closes #231 
- Closes #240 
Sync Actor - works:
```python
from apify_client import ApifyClient
TOKEN = '...'
ACTOR_ID = '...'
def actor_run_abort(apify_client: ApifyClient, actor_id: str) -> None:
actor_client = apify_client.actor(actor_id)
actor_client.call(wait_secs=1)
last_run = actor_client.last_run(status='RUNNING', origin='API')
aborted_info = last_run.abort()
print(f'aborted_info: {aborted_info}')
if __name__ == '__main__':
apify_client = ApifyClient(TOKEN)
actor_run_abort(apify_client, ACTOR_ID)
```
Async Actor - works:
```python
import asyncio
from apify_client import ApifyClientAsync
TOKEN = '...'
ACTOR_ID = '...'
async def actor_run_abort_async(apify_client: ApifyClientAsync, actor_id: str) -> None:
actor_client = apify_client.actor(actor_id)
await …
```
> fix: getting storages of last run

- CHANGELOG.md
- src/apify_client/clients/resource_clients/webhook.py
- src/apify_client/clients/resource_clients/webhook_collection.py
Adds the `headers_template` kwarg and is included in the payload on POST/PUT to the webhook endpoints.
* The API for create webhook supports headersTemplate parameter. Related docs at https://docs.apify.com/api/v2#tag/WebhooksWebhook-collection/operation/webhooks_post
* The API for update webhook supports headersTemplate parameter. Related docs at https://docs.apify.com/api/v2#tag/WebhooksWebhook-object/operation/webhook_put
> feat: adds headers_template to webhooks and webhooks_collection

- src/apify_client/clients/resource_clients/actor.py
- src/apify_client/clients/resource_clients/actor_collection.py
- src/apify_client/clients/resource_clients/task.py
- src/apify_client/clients/resource_clients/task_collection.py
This PR adds Actor Standby parameters to Actors and tasks.
> feat: add actor standby

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/index.md
- src/apify_client/client.py
- src/apify_client/clients/base/actor_job_base_client.py
- src/apify_client/clients/resource_clients/actor.py
- src/apify_client/clients/resource_clients/actor_collection.py
- src/apify_client/clients/resource_clients/actor_env_var.py
- src/apify_client/clients/resource_clients/actor_version.py
- src/apify_client/clients/resource_clients/actor_version_collection.py
- src/apify_client/clients/resource_clients/build.py
- src/apify_client/clients/resource_clients/build_collection.py
- src/apify_client/clients/resource_clients/run.py
- src/apify_client/clients/resource_clients/run_collection.py
- src/apify_client/clients/resource_clients/schedule.py
- src/apify_client/clients/resource_clients/schedule_collection.py
- src/apify_client/clients/resource_clients/task.py
- src/apify_client/clients/resource_clients/task_collection.py
- src/apify_client/clients/resource_clients/webhook.py
- src/apify_client/clients/resource_clients/webhook_collection.py
- website/src/pages/index.js
This was a chore indeed. A second pair of eyes would be welcome to make sure I haven't mixed something up.
> chore: Fix capitalization - actor -> Actor

- CHANGELOG.md
- src/apify_client/clients/resource_clients/dataset.py
We're adding an option to unwind multiple fields when listing the dataset items. This adds an option to DatasetClient to pass those multiple fields in the unwind parameter.
> feat: Allow passing list of fields to unwind parameter

- Makefile
Fixes the reference documentation build errors caused by the switch to `poetry` as the sole package manager.
> docs: fix docs build with `poetry run`

- pyproject.toml
- scripts/check_async_docstrings.py
- src/apify_client/clients/resource_clients/request_queue.py
- RQ's batch add requests can handle more than 25 requests.
- It was implemented in the same way as in the TS client.
- Applies for both sync & async versions.
- I do not use multi-threading for the sync version, since it is out of the scope of this issue. If users want performance, they should go with the client's async version. But if we decide it is worth to implement it, let's open another issue.
- Closes: #264
It was tested on this code sample (plus the sync alternative):
```python
import asyncio
from apify_client import ApifyClientAsync
from crawlee._utils.crypto import get_random_id
TOKEN = '...'
async def main() -> None:
apify_client = ApifyClientAsync(token=TOKEN)
rqs_client = apify_client.request_queues()
rq = await rqs_client.get_or_create(name='my-rq')
rq_client = …
```
> fix: batch add requests can handle more than 25 requests

- .github/workflows/run_release.yaml
Fixes:
```
The workflow is not valid. .github/workflows/run_release.yaml (Line: 81, Col: 9): Job 'publish_to_pypi' depends on unknown job 'async_docstrings'.
```
> ci: fix reference in run release

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Fixes type-wise links between documentation pages (see https://github.com/apify/apify-client-js/issues/591 for more context ).
> docs: bump `@apify/docusaurus-plugin-typedoc-api`

- src/apify_client/clients/resource_clients/user.py
Resolves https://github.com/apify/apify-client-js/issues/329 - add `update_limits` function to `UserClient`, which does `PUT: /v2/users/:userId/limits`
Api docs PR here: https://github.com/apify/openapi/pull/103
Client JS PR here: https://github.com/apify/apify-client-js/pull/595
Console api docs PR here: https://github.com/apify/apify-core/pull/18038
Endpoint is already implemented, only api docs and clients were missing
> feat: add user.update_limits

- src/apify_client/clients/resource_clients/run.py
Resolves https://github.com/apify/apify-core/issues/18593 by adding the charge endpoint to the run client.
Issue to add docs URL https://github.com/apify/apify-client-python/issues/305
> feat: Add charge method to the run client for "pay per event"

- src/apify_client/clients/resource_clients/dataset.py
Part of https://github.com/apify/apify-core/issues/18807 - Implementation of new API endpoint `v2/datasets/{datasetId}/statistics`
> feat: add GET: dataset.statistics

- src/apify_client/clients/resource_clients/build.py
Recently we've introduced new endpoint:
`/v2/actor-builds/:buildId/openapi-specification`
**This PR adds this endpoint to BuildClient**
P.S. The link to the documentation is correct, but docs are not yet merged into production. I'll merge this PR after the docs are merged.
> feat: add `get_open_api_specification` method to `BuildClient`

- src/apify_client/clients/resource_clients/build.py
Recently, we created new endpoints:
`/v2/acts/:actorId/builds/:buildId/openapi-specification`
`/v2/actor-builds/:buildId/openapi-specification`
Than we've received a feedback to rename endpoints to `/openapi.json`.
**This PR renames OpenAPI endpoints from `*/openapi-specification` to `*/openapi.json`*
More context [here](https://apify.slack.com/archives/C01VBUV81UZ/p1737975106009729)
> refactor: rename /openapi-specification -> /openapi.json

- src/apify_client/_http_client.py
- src/apify_client/_statistics.py
- src/apify_client/client.py
- tests/unit/test_statistics.py
- Add `Statistics` for gather HTTP rate limit errors
- Linked Issues is in the sdk, but the implementation should be in the client
- https://github.com/apify/apify-sdk-python/issues/318
- Add tests for `Statistics`
> feat: add rate limit statistics

- src/apify_client/clients/resource_clients/run.py
In the current state, the API call crashes because the `data` field is not present in the response.
> fix: Fix return type of charge API call

- docs/02_concepts/code/06_logging_formatter.py
- docs/pyproject.toml
Set line length to docs related code to 90 to have each code example fully visible without the need to use slider.
Update existing examples to be compliant.
> docs: Set line length to docs related code to 90

- pyproject.toml
- src/apify_client/_utils.py
- src/apify_client/clients/resource_clients/task.py
- uv.lock
There is a new rule [TC006](https://docs.astral.sh/ruff/rules/runtime-cast-value/).
> chore: update Ruff to v0.10

- pyproject.toml
- src/apify_client/_errors.py
- src/apify_client/client.py
- src/apify_client/clients/base/base_client.py
- src/apify_client/clients/resource_clients/actor_env_var.py
- src/apify_client/clients/resource_clients/request_queue.py
- src/apify_client/clients/resource_clients/user.py
- Currently, our docstrings use a mix of imperative and indicative moods basically randomly.
- PEP 257 recommends using the imperative mood for the first line of docstrings, which is also enforced by the Ruff rule [D401](https://docs.astral.sh/ruff/rules/non-imperative-mood/#non-imperative-mood-d401). So I believe the imperative form is more suitable for the docs purposes.
- In most cases, I have simply changed the verb form, but a few cases required more rewording.
- I updated the pyproject configuration to enforce it.
> docs: Use and enforce imperative mood

- src/apify_client/clients/resource_clients/request_queue.py
- tests/unit/test_client_request_queue.py
- tests/unit/test_client_timeouts.py
Remove retries from `batch_add_requests` (such retries already exist on the http client level).
Add deprecation warnings when retires related arguments are used.
Align sync and async version to not ignore exceptions from the http client. 
Add tests.
- Closes: #390
> refactor: Remove redundant retries from `batch_add_requests`

- src/apify_client/_utils.py
- src/apify_client/clients/resource_clients/actor.py
Add `validate_input` endpoint
- Closes: #151
> feat: Add `validate_input` endpoint

- src/apify_client/clients/resource_clients/key_value_store.py
Add `collection` and `prefix` query params for listing key-value store keys based on https://github.com/apify/actor-whitepaper/blob/master/pages/KEY_VALUE_STORE_SCHEMA.md#api-implications
Api docs: https://github.com/apify/apify-docs/pull/1564
Api impl: https://github.com/apify/apify-core/pull/20726
> feat: add list kv store keys by collection or prefix

- src/apify_client/_utils.py
Add usage of headers template
https://docs.apify.com/platform/integrations/webhooks/actions#headers-template
> feat: being able to add headers template in webhooks created dynamically

- src/apify_client/clients/resource_clients/actor_collection.py
Added new sorting param sortBy for the new feature described in this [Issue](https://app.zenhub.com/workspaces/platform-team-5f6454160d9f82000fa6733f/issues/gh/apify/apify-core/20997)
I will wait until [Apify-Core PR](https://github.com/apify/apify-core/pull/21566) is deployed and then will merge this.
One note, I am not sure if I added the sortBy parameter correctly. Example code below:
`return await self._list(my=my, limit=limit, offset=offset, desc=desc, sortBy=sort_by)`
I tried to follow similar examples with a camel case api parameter. Please let me know if this is not the correct syntax.
> feat: allow sorting of Actors collection

- src/apify_client/clients/resource_clients/key_value_store.py
related to https://github.com/apify/apify-docs/pull/1649
> feat: Add `KeyValueStoreClient.record_exists`

- src/apify_client/clients/resource_clients/dataset.py
- uv.lock
- Deprecate passing a simple string to the `unwind` parameter for `DatasetClient`
- Closes: #255
> refactor!: Remove support for passing a single string to the `unwind` parameter in `DatasetClient`

- docs/04_upgrading/upgrading_to_v2.md
- Update "Upgrading to v2" guide
> docs: Update "Upgrading to v2" guide

- src/apify_client/clients/resource_clients/key_value_store.py
- src/apify_client/clients/resource_clients/request_queue.py
> fix: casing in `exclusiveStartKey` API param

- src/apify_client/clients/resource_clients/key_value_store.py
- tests/integration/test_key_value_store.py
- Add `KeyValueStoreClient.get_record_public_url`.
- Add `KeyValueStoreClientAsync.get_record_public_url`.
- Add tests.
Closes: #497
> feat: Add `KeyValueStoreClient(Async).get_record_public_url`
